fix: Filtered Policy Support
pycasbin/sqlalchemy-adapter pull request #24
Opened 2021-01-09 04:28 UTC by yyellowsun

fix: [#15](https://github.com/pycasbin/sqlalchemy-adapter/pull/15)

2021-01-09 04:28 UTC, yyellowsun commented
@techoner  please help review the code.

2021-01-09 06:16 UTC, hsluoyz commented
@yyellowsun plz fix CI.

2021-01-09 06:53 UTC, hsluoyz commented
@yyellowsun plz fix the code coverage drop: 

![image](https://user-images.githubusercontent.com/3787410/104085441-6ba6f380-528a-11eb-8c99-ee2886be897c.png)

2021-01-09 14:57 UTC, techoner requested changes

2021-01-09 14:57 UTC, techoner commented on casbin_sqlalchemy_adapter/adapter.py
Where there is no need to escape, please use single quotation marks (`' '`), same everywhere else !

2021-01-09 14:57 UTC, techoner commented on tests/test_adapter.py
> +        self.assertTrue(e.enforce("alice", "data1", "read"))
I think arrays should be supported in Filter, refer to [Gorm Adapter](https://github.com/casbin/gorm-adapter/blob/master/adapter_test.go#L180).

2021-01-09 16:08 UTC, hsluoyz commented
@yyellowsun plz revise.

2021-01-12 14:50 UTC, yyellowsun commented
@techoner please help to review again.I don't know if it's ok,maybe something wrong in the 'g' ptype.
And I add some test examples,but coverage still droped.

2021-01-12 15:31 UTC, merged