feat: support filter sets
pycasbin/sqlalchemy-adapter pull request #30
Opened 2021-03-01 14:31 UTC by wakemaster39

resolves #29

2021-03-01 14:31 UTC, wakemaster39 commented
Just a question, if there is a reason to keep the length checks and instead just use truthiness?

2021-03-02 02:13 UTC, hsluoyz commented
@techoner @Zxilly plz review.

2021-03-02 02:38 UTC, Zxilly requested changes

2021-03-02 02:38 UTC, Zxilly commented on casbin_sqlalchemy_adapter/adapter.py
> +        return ", ".join(arr)
Maybe there is no need to change these

2021-03-02 02:40 UTC, Zxilly commented on casbin_sqlalchemy_adapter/adapter.py
> +        return ", ".join(arr)
I think the other part look good to me.

2021-03-02 04:54 UTC, merged

2021-03-02 04:54 UTC, Zxilly approved these changes

2021-03-02 04:54 UTC, hsluoyz commented
@Zxilly plz make a new release.

2021-03-02 04:59 UTC, hsluoyz commented
@techoner can you help make a new release?

https://pypi.org/project/casbin-sqlalchemy-adapter/

2021-03-02 11:27 UTC, wakemaster39 commented
Sweet, thanks @hsluoyz. Sorry black just auto runs on all my code, I didn't even notice the change in quotes