feat: finish up update_policy and update_policies
pycasbin/sqlalchemy-adapter pull request #48
Opened 2021-07-20 12:13 UTC by ffyuanda

Fix: #41 
Signed-off-by: ffyuanda <46557895+ffyuanda@users.noreply.github.com>

2021-07-20 12:15 UTC, ffyuanda commented
@hsluoyz @techoner plz review

2021-07-20 14:46 UTC, Zxilly approved these changes

2021-07-21 08:06 UTC, techoner requested changes

2021-07-21 08:06 UTC, techoner commented on casbin_sqlalchemy_adapter/adapter.py
> +        """removes a policy rule from the storage."""
Please modify it to "remove policy rules from the storage."

2021-07-21 09:43 UTC, techoner approved these changes

2021-07-21 09:43 UTC, merged