feat: Add the option for softdelete
pycasbin/sqlalchemy-adapter pull request #72
Opened 2024-07-06 17:10 UTC by trbtm

I would like to have the option for having soft delete rules in the database to be able to possibly track fields like

- deleted_by, deleted_at
- updated_by, updated_at

etc.

2024-07-07 06:52 UTC, leeqvip commented
@trbtm  Hi,
1. Can the database operations be separated? The Adapter only needs to call the corresponding query or modification method.
2. Regarding soft deletion, some fields are marked as `true` or `false`, while others set the `deleted_at` time.
3. The updated_at you mentioned is not shown here.

2024-07-07 09:07 UTC, trbtm commented
@leeqvip Hi,

I added an example demonstrating my approach. To your points:

1. I think that would be difficult since deleted rules need to be filtered when the adapter is querying the database e.g. in `Adapter.remove_policies` you want to make sure that only non deleted rules get affected
2. I think this gets clear when you look the the example I provided
3. Same as above.

Best
Thore

2024-07-07 10:24 UTC, leeqvip requested changes

2024-07-07 10:24 UTC, leeqvip commented on casbin_sqlalchemy_adapter/adapter.py
> +        db_class_softdelete_attribute=None,
Here you can judge according to the `is_deleted` attribute of `db_class`, the default value is None

2024-07-07 10:24 UTC, leeqvip commented on examples/softdelete.py
> +e = casbin.Enforcer("path/to/model.conf", adapter)
Please write it directly in the readme, in a separate section

2024-07-08 14:01 UTC, leeqvip approved these changes

2024-07-08 14:02 UTC, merged